version: '3.9'
services:
  java-maven-app:
    image: uzair102/u_repo:jma-2.2
    ports:
      - 8080:8080
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=my_pwd
